version: '3'
services:
  node1:
    image: byterui/hotstuff_node
    command: ["/usr/bin/run_node.sh", "alice","0"]
    environment:
    - HOTSTUFF_DURATION=1000
    cap_add:
    - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: "0.5"
    ports:
      - 30333:30333
      - 9933:9933
      - 9944:9944
      - 9615:9615
    networks:
      - mynetwork      
  node2:
    image: byterui/hotstuff_node
    command: ["/usr/bin/run_node.sh", "bob","50"]
    environment:
    - HOTSTUFF_DURATION=1000    
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "0.5"
    ports:
      - 30334:30333
      - 9934:9933
      - 9945:9944
      - 9616:9615
    networks:
      - mynetwork      
  node3:
    image: byterui/hotstuff_node
    command: ["/usr/bin/run_node.sh", "charlie","50"]
    environment:
    - HOTSTUFF_DURATION=1000    
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "0.5"    
    ports:
      - 30335:30333
      - 9935:9933
      - 9946:9944
      - 9617:9615
    networks:
      - mynetwork      
  node4:
    image: byterui/hotstuff_node
    command: ["/usr/bin/run_node.sh", "dave","0"]
    environment:
    - HOTSTUFF_DURATION=1000    
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "0.5"    
    ports:
      - 30336:30333
      - 9936:9933
      - 9947:9944
      - 9618:9615
    networks:
      - mynetwork      
  node5:
    image: byterui/hotstuff_node
    command: ["/usr/bin/run_node.sh", "eve","50"]
    environment:
    - HOTSTUFF_DURATION=1000    
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "0.5"    
    ports:
      - 30337:30333
      - 9937:9933
      - 9948:9944
      - 9619:9615
    networks:
      - mynetwork      
  node6:
    image: byterui/hotstuff_node
    command: ["/usr/bin/run_node.sh", "ferdie","50"]
    environment:
    - HOTSTUFF_DURATION=1000    
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "0.5"    
    ports:
      - 30338:30333
      - 9938:9933
      - 9949:9944
      - 9620:9615
    networks:
      - mynetwork

networks:
  mynetwork:      