version: '3'
services:
  base_node: &base_node
    image: byterui/substrate_node_custom
    cap_add:
    - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '0.3'
    networks:
      - mynetwork

  node1:
    <<: *base_node
    command: ["/usr/bin/run_node.sh", "0"]
    ports:
      - 30333:30333
      - 9933:9933
      - 9944:9944
      - 9615:9615
    volumes:
      - ../substrate_volume/node_1:/data
      - ../substrate_spec:/chain_spec    

  node2:
    <<: *base_node
    command: ["/usr/bin/run_node.sh", "0"]
    ports:
      - 9945:9944
    volumes:
      - ../substrate_volume/node_2:/data
      - ../substrate_spec:/chain_spec

  node3:
    <<: *base_node
    command: ["/usr/bin/run_node.sh", "25",]
    volumes:
      - ../substrate_volume/node_3:/data
      - ../substrate_spec:/chain_spec

  node4:
    <<: *base_node
    command: ["/usr/bin/run_node.sh", "25"]
    volumes:
      - ../substrate_volume/node_4:/data
      - ../substrate_spec:/chain_spec

  node5:
    <<: *base_node
    command: ["/usr/bin/run_node.sh", "25"]
    volumes:
      - ../substrate_volume/node_5:/data
      - ../substrate_spec:/chain_spec

  node6:
    <<: *base_node
    command: ["/usr/bin/run_node.sh", "25"]
    volumes:
      - ../substrate_volume/node_6:/data
      - ../substrate_spec:/chain_spec

  node7:
    <<: *base_node
    command: ["/usr/bin/run_node.sh", "25"]
    volumes:
      - ../substrate_volume/node_7:/data
      - ../substrate_spec:/chain_spec

  node8:
    <<: *base_node
    command: ["/usr/bin/run_node.sh", "25"]
    volumes:
      - ../substrate_volume/node_8:/data
      - ../substrate_spec:/chain_spec

  node9:
    <<: *base_node
    command: ["/usr/bin/run_node.sh", "25"]
    volumes:
      - ../substrate_volume/node_9:/data
      - ../substrate_spec:/chain_spec

  node10:
    <<: *base_node
    command: ["/usr/bin/run_node.sh", "25"]
    volumes:
      - ../substrate_volume/node_10:/data
      - ../substrate_spec:/chain_spec

  node11:
    <<: *base_node
    command: ["/usr/bin/run_node.sh", "25"]
    volumes:
      - ../substrate_volume/node_11:/data
      - ../substrate_spec:/chain_spec

  node12:
    <<: *base_node
    command: ["/usr/bin/run_node.sh", "25"]
    volumes:
      - ../substrate_volume/node_12:/data
      - ../substrate_spec:/chain_spec

networks:
  mynetwork:         